general.import = [
  # "~/.config/alacritty/Themes/catppuccin_mocha.toml",
  # "~/.config/alacritty/Themes/tokyo_night.toml",
  # "~/.config/alacritty/Themes/tokyo_night_enhanced.toml",
  # "~/.config/alacritty/Themes/gruvbox-dark.toml",
  # "~/.config/alacritty/Themes/kanagawa_wave.toml",
  "~/.config/alacritty/Themes/solarized_osaka.toml",
]

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

# previous "font CaskaydiaCove Nerd Font"

