add_newline = true
command_timeout = 200
palette = "gruvbox_material"
format = """\
󰣇 \
$directory\
$git_branch$git_status\
$line_break\
$character\n
"""
continuation_prompt = '▶▶ '

[character]
success_symbol = '[❯](bold yellow)'   #(bold green)
error_symbol = '[❯](bold red)'
vicmd_symbol = '[❮](bold yellow)'     #"[N] >>>"

[directory]
style = "bold #d4be98"
format = "[$path]($style) "
truncation_length = 0
truncate_to_repo = false

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[git_branch]
# symbol = "" # default symbol is ""
style = "bold #7daea3" #9198a1
format = '[$symbol$branch]($style) '


[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[( $all_status$ahead_behind )](fg:#ea6962)]($style)'
style = "bg:#394260"

[line_break]
disabled = false

[palettes.gruvbox_material]
yellow = "#d79921"
red = "#ea6962"
