general.import = [
  # "~/.config/alacritty/Themes/catppuccin_mocha.toml",
  # "~/.config/alacritty/Themes/tokyo_night.toml",
  # "~/.config/alacritty/Themes/tokyo_night_enhanced.toml",
  # "~/.config/alacritty/Themes/gruvbox-dark.toml",
  # "~/.config/alacritty/Themes/kanagawa_wave.toml",
  # "~/.config/alacritty/Themes/solarized_osaka.toml",
  "~/.config/omarchy/current/theme/alacritty.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 1
# dynamic_padding = true
decorations = "None"
opacity = 0.96

[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 10

# previous "font = CaskaydiaCove Nerd Font"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

